## Serverless config
## https://serverless.com/framework/docs

## Name for overall service (collection of functions)
service: canteenbot

## AWS details
provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1
  profile: ${file(env.yml):profile}
  stage: ${file(env.yml):stage}

  ## Service-wide environment variables
  environment:
    CORE_URL: ${file(env.yml):CORE_URL}

## Individual parts of the service
functions:
  ## CanteenBot's core
  core:
    handler: dist/core.handler
    events:
      - http:
          path: /core
          method: get
    environment:
      DATA_URL: https://canteenbot-data.s3-eu-west-2.amazonaws.com/

  ## Slash-command listener
  slack:
    handler: dist/slack.handler
    events:
      - http:
          path: /slack
          method: post
    environment:
      TIMES_TEAM: ${file(env.yml):TIMES_TEAM}

  ## Post to Slack on a schedule
  slack-notifier:
    handler: dist/slack-notifier.handler
    events:
      - schedule: cron(15 11 * * ? *)
    environment:
      WEBHOOK_URL: ${file(env.yml):WEBHOOK_URL}

  ## Alexa skill
  alexa:
    handler: dist/alexa.handler
    events:
      - alexaSkill

  ## Menu scraper
  scraper:
    handler: dist/scraper.handler
    events:
      - schedule: cron(0 * * * ? *)

## Bundling options
package:
  # individually: true
  exclude:
    - node_modules/**
    - assets/**
    - data/**
    - package.json
    - .gitignore
    - README.md
  # include:
  #   lib/**


## Examples of event types
# events:
#   - http:
#     path: users/create
#     method: get
#   - s3: ${env:BUCKET}
#   - schedule: rate(10 minutes)
#   - sns: greeter-topic
#   - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#   - alexaSkill
#   - iot:
#     sql: "SELECT * FROM 'some_topic'"

## Examples of adding CloudFormation resource templates
# resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
